### ISSUE TITLE
Ad integration in cuepoints

### ISSUE THREAD

**Issue by nafisakanwal** [cladera/videojs-cuepoints#14]
Hi
I need to add ad tag in cue points. Here in the documentation i have not found any of way .
Please help me .its very urgent

**Comment by cladera** [comment]
Hi, 

Didn't see you've already opened a new issue, apologises.

What do you mean with "ad tag" I'm not familiarised with that concept.

**Comment by nafisakanwal** [comment]
Hi Cladera 
Thanks for the reply 
i am talking about mid roll ads , how can i implement in cue points. is there have any way ?

**Comment by nafisakanwal** [comment]
Cladera  , actually i want to to show  'video ad' in my videos , by using cue points.
is it possible  ?

**Comment by cladera** [comment]
This plugin has not implemented specific functionality for advertising. However, you can develop custom interactions with video timeline in JavaScript. So everything you can execute in JavaScript you can do it as a cuepoint.
