### ISSUE TITLE
delete added cue point

### ISSUE THREAD

**Issue by RushabhJoshi** [cladera/videojs-cuepoints#18]
hi,
can you please provide the documentation to remove added cue points.
thanks

**Comment by cladera** [comment]
Hello @RushabhJoshi,

As you've probably noticed, the whole project needs a review in terms of documentation. Pull requests will be totally welcome. 

In the meantime, to destroy all cuepoints added, you can use `player.destroyCuepoints()`.

Regards.

**Comment by vince-scarpa** [comment]
After adding cue points you can remove them using the players removeCue TextTrack prototype 

`
// First get the tracks list
var tracks = player.textTracks();

// The cue id you want to delete
var cue_id = 2;

// loop through the tracks
for (var i = 0; i < tracks.length; i++) {
   if( tracks[i].id == 'some_id' ) {
     tracks[i].removeCue( tracks[i].cues_[cue_id] );
   }
}`

**Comment by cladera** [comment]
`videojs-cuepoints` plugin does not use TextTrack API yet. Next major version will use videojs' text track support.
