### ISSUE TITLE
Not working on mp4 videos

### ISSUE THREAD

**Issue by RushabhJoshi** [cladera/videojs-cuepoints#19]
Hello,

I am working on video appliction which supports youtube, vimeo and custom .mp4 videos.

This plugin is working fine with youtube and vimeo. also was working fine with .mp4
but suddenly it started giving me error player.addCuepoint is not a function. first of all I thought it was webkit browser mistake. I switch the browser still giving me same error.

e.g.
http://www.w3schools.com/html/mov_bbb.mp4

Thank you

**Comment by cladera** [comment]
Perhaps, it is because you upgraded videjos to 5.0, did you?

**Comment by IGZgustavomarin** [comment]
This plugin works only with VideoJS 4.0?

**Comment by cladera** [comment]
It works now, thanks to @dwkns https://github.com/cladera/videojs-cuepoints/pull/21

**Comment by IGZgustavomarin** [comment]
:+1: :rocket:

**Comment by RushabhJoshi** [comment]
Sorry for the late reply. The problem still cause and I don't know why? may be the file was broken. anyways somehow I solved the problem with another fix.

thank you
