### ISSUE TITLE
ad url help required

### ISSUE THREAD

**Issue by nafisakanwal** [cladera/videojs-cuepoints#24]
HI cladera 
I want to use this plugin for play creative ads , it is  a sort of dfp url , how can i pass the ad url into using the cuepoint plugin 
thanks in advance

**Comment by cladera** [comment]
Hi @nafisakanwal sorry for the late response. 

This plugin is not specifically intended for advertising. I am not familiar with dfp urls so I cannot help you any further.

Thank you.
