### ISSUE TITLE
Installing via NPM

### ISSUE THREAD

**Issue by ghost** [cladera/videojs-cuepoints#25]
Is there any information or possibility of installing this plugin via npm and importing it using ES6 syntax?

**Comment by williammustaffa** [comment]
I'm using this with ES6. 
`npm install videojs-overlay --save` and using like:
`import videojs from 'video.js';
import 'videojs-overlay';` 
worked.

**Comment by cladera** [comment]
Hi @ghost! Sorry for the late response. 

No, it is not possible to install this plugin via npm. 

Since HTML5 format introduces TextTracks this plugin makes no sense anymore so I am not adding new features.
