### ISSUE TITLE
VideoJS with cuepoints

### ISSUE THREAD

**Issue by maheshiv** [cladera/videojs-cuepoints#9]
Hi ,
I am using videojs player for one of the application. Now i need to add cuepoints for videojs player , for this i found this plugin ttps://github.com/cladera/videojs-cuepoints . Here they did not mention about how to add cuepoint links outside the video player (so i can click cuepoint link and video will play from that). Is there anyway to achieve this ?

**Comment by nafisakanwal** [comment]
Hi
I need to add ad tag in cue points. Here in the documentation i have not found any of way .
Please help me

**Comment by cladera** [comment]
Hi @nafisakanwal ,

I'm not familiarised with "ad tag" concept. Could you explain what do you want to accomplish?
 
Anyway, this issue is already closed, could you please open a new one?

Thanks.
